server:
  port: 7002

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server7001:7001/eureka/,http://eureka-server7002:7002/eureka/
    register-with-eureka: false
    fetch-registry: false