server:
  port: 8004

spring:
  application:
    name: cloud-provider-payment

  cloud:
    zookeeper:
      connect-string: 192.168.3.172:2181

  datasource:  #数据源
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://134.175.137.147:3306/archives?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: lzzj123456
    druid:  #德鲁伊数据源定制
      filters: stat #配置监控统计拦截的filters

      initialSize: 1 #初始化大小
      minIdle: 1 #最小
      maxActive: 20 #最大

      maxWait: 60000 #配置获取连接等待超时的时间

      timeBetweenEvictionRunsMillis: 60000 #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒

      minEvictableIdleTimeMillis: 300000 #配置一个连接在池中最小生存的时间，单位是毫秒
      #      maxEvictableIdleTimeMillis: 900000

      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false

      poolPreparedStatements: true #打开PSCache
      maxOpenPreparedStatements: 20 #指定每个连接上PSCache的大小

      asyncInit: true