server:
  port: 80

spring:
  application:
    name: consumer-order
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka-server7001:7001/eureka/,http://eureka-server7002:7002/eureka/
  instance:
    instance-id: c-order80
    prefer-ip-address: true