server:
  port: 80

spring:
  application:
    name: consumer-hystrix-order
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka-server7001:7001/eureka/,http://eureka-server7002:7002/eureka/
  instance:
    instance-id: c-hystrix-order80   #eruka网站页面 服务商 显示服务名
    prefer-ip-address: true   #eruka网站页面 显示服务器ip

#设置feign客户端超时时间(OpenFeign默认支持ribbon)
ribbon:  #默认是1秒，如果超过1秒服务端没响应，立马报错
  #指的是建立连接所用的时间，适用于网络状况正常的情况下，两端连接所用的时间
  ReadTimeout: 5000
  #指的是建立连接后从服务器读取到可用资源所用的时间
  connectTimeout: 5000

logging:
  level:
    #feign日志以书面级别监控哪个接口
    com.fcl.springcloud.order.service.OrderService: debug
feign:
  hystrix:
    enabled: true #开启 支持断路器
